ALTER TABLE Deck ADD "colors" TEXT NOT NULL DEFAULT '';
ALTER TABLE Deck ADD "url" TEXT NOT NULL DEFAULT '';
ALTER TABLE Deck ADD "bracket" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE Game ADD "comment" TEXT NOT NULL DEFAULT '';
ALTER TABLE Game ADD "duration" INTEGER NOT NULL DEFAULT 0;
